### ISSUE TITLE
Data validation check - Missingness not beyond expected threshold

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#31]

**Comment by jasonmlee** [comment]
Since our preprocessor does not contain a SimpleImputer, we have a zero tolerance for missingness.

Error cases (NaN values or incorrect values) are dropped from the original dataframe after validation.

![CleanShot 2024-11-29 at 11 57 07](https://github.com/user-attachments/assets/6fe76ec1-793c-482e-a471-5bc6592e83ff)
