### ISSUE TITLE
Target/response variable follows expected distribution

### ISSUE THREAD

**Issue by Forsythia-olive** [UBC-MDS/DSCI522-2425-39-FMJ#48]
Am stuck on this I need suggestions on how to go about this

**Comment by jasonmlee** [comment]
I made this change in my latest commit:

- Instead of showing the entire target column, I'm now using value_counts to display the distribution of the target.
- It is reasonable to see that there are more 'Adults' than `Seniors`
- Let me know if you think this fulfills this data validation criteria.

![CleanShot 2024-11-29 at 13 37 26](https://github.com/user-attachments/assets/1df1dbcd-7095-4c6a-9b1e-fb057e840069)

**Comment by Forsythia-olive** [comment]
<img width="704" alt="Screenshot 2024-11-29 at 4 37 58 PM" src="https://github.com/user-attachments/assets/f945057a-fc3d-4745-b5f3-f147da53b8cb">

 I added this for the distribution check in addition to what is above,
 
Guys, what do you think
